auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  aws:
    endpoint: minio:9000
    bucketnames: loki
    access_key_id: minioadmin
    secret_access_key: minioadmin
    s3forcepathstyle: true
    region: us-east-1
    insecure: true
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/loki/compactor
  delete_request_store: aws

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 10m
  chunk_retain_period: 1m
  wal:
    dir: /loki_wal
    enabled: true