services:
  api:
    build:
      context: ./app
    container_name: payment-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://payments:payments@db:5432/paymentsdb
      - WEB_CONCURRENCY=2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 256m

  db:
    image: postgres:18-alpine
    container_name: payment-db
    environment:
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
      - POSTGRES_DB=paymentsdb
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments -d paymentsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    mem_limit: 256m

  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=7d"
      - "--storage.tsdb.min-block-duration=2h"
      - "--storage.tsdb.max-block-duration=2h"
      - "--web.enable-remote-write-receiver"
    restart: unless-stopped
    mem_limit: 512m

  grafana:
    image: grafana/grafana:13.0.1-security-01
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    mem_limit: 256m
  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    mem_limit: 128m

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.19.1
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://payments:payments@db:5432/paymentsdb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    mem_limit: 64m

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.55.1
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    mem_limit: 256m

  loki:
    image: grafana/loki:3.7.2
    container_name: loki
    user: "0"
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/config.yml
      - loki_wal:/loki_wal
    command: -config.file=/etc/loki/config.yml
    restart: unless-stopped
    mem_limit: 256m
    
  tempo:
    image: grafana/tempo:3.0.0
    container_name: tempo
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/tempo-config.yml:/etc/tempo/config.yml
    command: -config.file=/etc/tempo/config.yml
    restart: unless-stopped
    mem_limit: 256m

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.153.0
    container_name: otel-collector
    user: "0"
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    restart: unless-stopped
    mem_limit: 256m

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    mem_limit: 256m

  thanos-sidecar:
    image: quay.io/thanos/thanos:v0.41.0
    container_name: thanos-sidecar
    user: "0"
    volumes:
      - ./thanos/bucket-config.yml:/etc/thanos/bucket-config.yml
      - prometheus_data:/prometheus
    command:
      - sidecar
      - --tsdb.path=/prometheus
      - --prometheus.url=http://prometheus:9090
      - --objstore.config-file=/etc/thanos/bucket-config.yml
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
    depends_on:
      - prometheus
      - minio
    restart: unless-stopped
    mem_limit: 128m

  thanos-store:
    image: quay.io/thanos/thanos:v0.41.0
    container_name: thanos-store
    volumes:
      - ./thanos/bucket-config.yml:/etc/thanos/bucket-config.yml
    command:
      - store
      - --data-dir=/tmp/thanos-store
      - --objstore.config-file=/etc/thanos/bucket-config.yml
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
    depends_on:
      - minio
    restart: unless-stopped
    mem_limit: 128m

  thanos-query:
    image: quay.io/thanos/thanos:v0.41.0
    container_name: thanos-query
    ports:
      - "10902:10902"
    command:
      - query
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      - --endpoint=thanos-sidecar:10901
      - --endpoint=thanos-store:10901
      - --query.replica-label=replica
    depends_on:
      - thanos-sidecar
      - thanos-store
    restart: unless-stopped
    mem_limit: 128m

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/thanos --ignore-existing;
      mc mb local/loki --ignore-existing;
      mc mb local/tempo --ignore-existing;
      echo 'Buckets thanos, loki y tempo creados';
      exit 0;
      "
    restart: on-failure

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  minio_data:
  loki_wal:
